name: "Deploy solution"
# Based on sample at https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/release-solution-to-prod.yml

on:
  workflow_dispatch:

env:
  BUILD_ENVIRONMENT_URL: https://orgac818224.crm17.dynamics.com
  USERNAME: algattik@oneweekbreathebuild.onmicrosoft.com

jobs:
  import:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: src
        solution-file: out/solutions/Breathe.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: out/solutions/Breathe.zip
        force-overwrite: true
        publish-changes: true

  seed:
    needs: import
    runs-on: ubuntu-latest

    steps:
    - name: 'Az CLI login'
      run: az login -u "${{env.USERNAME}}" -p "${{secrets.PASSWORD}}" --allow-no-subscriptions

    - name: 'Populate cr880_researchprojects'
      run: az rest --resource ${{env.BUILD_ENVIRONMENT_URL}} --url ${{env.BUILD_ENVIRONMENT_URL}}/api/data/v9.2/cr880_researchprojects --method POST --body @data/cr880_researchprojects.json

    - name: 'Install newman'
      run: npm install -g newman

    - name: 'Run newman'
      run: >
        token=$(az account get-access-token --resource ${{env.BUILD_ENVIRONMENT_URL}} --query accessToken -o tsv)
        newman run
          --folder "Seed Data"
          --environment data/Breathe.postman_environment.json 
          --env-var token="$token"
          --env-var url="${{env.BUILD_ENVIRONMENT_URL}}"
          data/Breathe.postman_collection.json
